replicas: 2

image:
  repository: 4volodin/ibs-blogjs
  tag: 0.2

hostname: ibs-blog.truedev.ru
cluster_issuer: letsencrypt-staging
stage_url: https://acme-staging-v02.api.letsencrypt.org/directory
prod_url: https://acme-v02.api.letsencrypt.org/directory
ssl_nodeport: 31444
nodeport: 31081
email:
resources:
  requests:
    cpu: "250m"
    memory: "512M"
  limits:
    cpu: "500m"
    memory: "512M"
