apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-nginx
  namespace: {{ .Chart.Name }}-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.cluster_issuer | default "letsencrypt-prod" }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ .Chart.Name }}-certificate
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: 80

