apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: {{ .Chart.Name }}-ingress-nginx
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-nginx
    app.kubernetes.io/part-of: {{ .Chart.Name }}-ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nodeport }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ .Values.ssl_nodeport }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-nginx
    app.kubernetes.io/part-of: {{ .Chart.Name }}-ingress-nginx
